server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(?:js|css|map|woff|woff2|ttf|eot|svg|png|jpg|jpeg|gif|webp|ico)$ {
        try_files $uri =404;

        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.csr.html;
    }
}
